dataBase:
    host: ENC[AES256_GCM,data:KhCsHdS/+IzBYkPSrsl+m3rQ7kFC7+4IOZ6W8ucAINrgvnKPf4Le0P4okQ7CdlETHyouyWzh,iv:yYrFxSNBuXtR2s45YV+4uJ5GjIETzhBwUXMeCvBtZpA=,tag:736/YZAHe9FwRYy7eFjyCA==,type:str]
    port: ENC[AES256_GCM,data:xalT/A==,iv:1qAI9D5xZBL9QxY/juf97RZRFsWR4DlvTsx/lLueb84=,tag:FFGbcivz6SgMM0M+I0360Q==,type:str]
    name: ENC[AES256_GCM,data:F4yrl4YH,iv:yO0q3PZIEZVwZ3p8blK+zUd4qYHoi5iffEWdyxKK1P4=,tag:v/H7cJ7LTws8I8193xldmw==,type:str]
    user: ENC[AES256_GCM,data:H0fcSeTq,iv:jQm8NoiIx8++Se8UZo/gidNedJsqTyAJXKXUfyP7zqU=,tag:kxp/Rrzph0VsKNbqBULlHQ==,type:str]
    userpass: ENC[AES256_GCM,data:NkDKnR3K,iv:E56F+eoS59JDoVsjtxhiCmmfavCNMEigqeXgiIKJP8w=,tag:YmK6iw2WAiI1C+5OvdJhag==,type:str]
    adminpass: ENC[AES256_GCM,data:gPKfJgxd,iv:xmjuQQP82Ro0URRbx3yV2amYKqpOgXr1bFWFbJqhS64=,tag:GHM9hRh9QCY2jL991ZGgGA==,type:str]
kafka:
    host: ENC[AES256_GCM,data:4FiJbbWmwLxsqIhVq2+witSTbavs/7lPMaC7HRwdlwwfe6DViA==,iv:nHBFTeJQS6co9VmisyOWsS/8d5GmyvSE70hNIu3Cs1c=,tag:oGx0r4jZ9VgVY+35HiuYFg==,type:str]
    port: ENC[AES256_GCM,data:E3/QVQ==,iv:wbsjPnqVZWOOcXH+V5QpBehhT3zZS9iqUwrn0MHbb9g=,tag:AbgmFERC2Smsc6ja8k6Epw==,type:str]
namespace: ENC[AES256_GCM,data:6UjczYz3,iv:bAoCu/ePL82EzYcV12PV7wJGoCdai7q9r/SLSzrCeuY=,tag:I5MA0ZpyKpbKtbDdn/wqSg==,type:str]
serviceName: ENC[AES256_GCM,data:YJ2Ds7++gLbHCNopdPU=,iv:zt9ru3J8zAUz7TN4y49eTWlPhHmazzPZli9Fzzj7NPE=,tag:tm6VDRL6qUz+g4bJFsM54g==,type:str]
deploymentName: ENC[AES256_GCM,data:LEYlKWnTVoVYQx2dYrhf0is=,iv:WkN63+9jd4tYHNZ2X9XCumSgMGQOPiNex9kbYCgX6ZM=,tag:2FWys7yoQdRAvZZZup2dtg==,type:str]
containerName: ENC[AES256_GCM,data:Cnus3kFdXDoQJF+WhM1hzg==,iv:XiiiWeU0VvP6jKZnM3+CpOE78Kc7p4tRw88Cg79iOyA=,tag:ALrrft5s6aLRUNPwxLqH2Q==,type:str]
configName: ENC[AES256_GCM,data:QZOhdB6jmdoJAznCmA==,iv:MbZVenbOpoEgWhw9RewS19PoI7vMBR8OoeQSz6kuo7E=,tag:KZg2WtyCGNmgRdp/rcUtVQ==,type:str]
secretName: ENC[AES256_GCM,data:MtTB+u9p9jA8Itr4VtSL+jhN,iv:YVniRQKt8yinQXVV5xFSdhr44m3ucH0t0oi/V4UxdDo=,tag:qnPuYwB3NC2KFlUWS4U29A==,type:str]
serviceMonitorName: ENC[AES256_GCM,data:JMl7IAimcmTjAjCn2VA=,iv:808DH3V2d5HMfZNgXUebYVdhiS/n+DpmUtBsgTWByPE=,tag:5gQkw8ywSXqtPI5B0gm2Kw==,type:str]
serviceMonitorLabel: ENC[AES256_GCM,data:etcNGCjJtn5VGrqWYAo=,iv:hekGLPA/ZBOUFpY2DeYbspbfpZmkPlPv5Sdlk4spvd8=,tag:noiLj/k8L9g8phiUL9Y43w==,type:str]
deploy:
    replicasCount: ENC[AES256_GCM,data:TQ==,iv:OBTzpajF2pMpfR2j/Tade6QSK6CCk61E82a3oynZlck=,tag:FcEqygTXGTPtu0lz2nJgfg==,type:int]
    serviceLabel: ENC[AES256_GCM,data:618zIHBn,iv:bhe2Kr3GRBxww/e17YSfGHiz5biRV8IOLoYGHafV/F4=,tag:n9nyScKfuP15QbsKrHzBgw==,type:str]
    podLabel: ENC[AES256_GCM,data:9syOnshe,iv:x3IDPDtQu9g7EtgXHJ9jcGRWP4wVuxUdJbeD6MnKld0=,tag:CXgPK+ndoICbPoKVd/cl0g==,type:str]
    deploymentLabel: ENC[AES256_GCM,data:RmtCHa4B,iv:Q/5s1+syNMfKdSDS/vd6TnFAznbjTMVWMDFSPmeyjyQ=,tag:zwJhTCaZF8kDo+FMo2KbHw==,type:str]
    containerPort: ENC[AES256_GCM,data:Eu1v+w==,iv:7xsDi9NTl0MFIDBC5puLQQVXJJuBK2ajfHXEI7mEBcY=,tag:IRx8cDOFk/2fWO4MabPfcg==,type:int]
    image:
        name: ENC[AES256_GCM,data:AXsPsbThqkdHbc8/Y/0UaLIXqJaAlpFjWdMJYBwdhAHB79tN7VQDFOU2uy+WOYB+2hOVKqXbaXs=,iv:MzN1HF1ipLCAt33ytW+mrhBLOTINCljXB2qcKFEN2/w=,tag:mAoSjPj0rFPDU4NcU6YxGg==,type:str]
        tag: ENC[AES256_GCM,data:Px96483wwSJ4q2p4I1GX/n9Yn/J+eTylmmBf5hEENfDPn50L0zlqsQ==,iv:2ZJ/4GRLDIxIkAJR2qRTJNxocIySLiMHoS+dBEmQ8bg=,tag:yHAYlgJ3EcrFKABQ2a5Cow==,type:str]
    service:
        type: ENC[AES256_GCM,data:+YqnWa/+cpmG,iv:/Jopgn5iVzHc9irZ0YvaXvlYDcfjwV9xZc0a4MssMsI=,tag:qfUkc6OpR0w6Uq1pHuqG9Q==,type:str]
        port:
            number: ENC[AES256_GCM,data:GOyk2A==,iv:T1GKkZ3vMXOcY21MFwGjjO08cSSEInHNBoBYiEZwXzQ=,tag:pSxHRtsCxYBt4w14++Q0Lg==,type:int]
            name: ENC[AES256_GCM,data:AxLCHZFK,iv:qd51LkLTTNOUqun+B8tKIuZL9f1vnd3Nza6zs9hFypQ=,tag:wEtKkZ7aVra6l6giiX/vhw==,type:str]
        metricPort:
            number: ENC[AES256_GCM,data:/LA3gw==,iv:lqAR7fGuVZ5IrUV4klLZWybghntL6WS+U6+837xeMQg=,tag:nDDj+EZqTcZoxvdq6temNg==,type:int]
            name: ENC[AES256_GCM,data:uQNIjt1MgnfiVNsjIp0=,iv:OUJbk8ks7xeFb5I+CrTiQTnt6380dQWiSwcBp+5ydbU=,tag:hhzkrjAwmMCahNg+K4tdXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yu4wcn3ykhlxfkne5te45v9vjcjuuv67h9ywl5kd09fnygr5df8q377uqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHBzQVNNYjIvWFF2YnRu
            Yk5pQUM2M3dXd3ZXT0hIY1FsTHUrelQyZ3hvCmplZTNJYzQ2T1VjWEdnak1wVi9E
            VEpERW1VVWh6N1pGTDhRTEk0SlFGSzQKLS0tIFhNaFpxRkpNYnBtWC9Ebk5FWkZn
            bHpVT3VzcjJXZGFBU0U5UkhqaldpSzQKj66S96kGo6JupWjsn0SnPnOOyRtejxvc
            bqT10wYsODQrjWXT7q18hN+WvZ70awKLtZzY0kUpsTVe5ktrHffgvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-26T12:47:47Z"
    mac: ENC[AES256_GCM,data:TpT4TJUEvylRCrbuXUGcL3UqRawAkLWMSqkOyjCTvCnvhltiOzw4yU/HLHeZ7HeQsK2AbKxF3QCNk54QreCLsuTWmnAf/eKqA0rYrAQhmBBg3aJGq1LgbDECTONt8aueSeIXi00sNDCZVdE8vRBKlC4U/G7rpgzuT0RxqQ844uM=,iv:NmVCHR0ywGkoaGaKzvM2CTaQLXyUAuh0iKX3+GEwM2I=,tag:2PPi+r0V8ZF09qhWEiI8SA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
