dataBase:
    host: ENC[AES256_GCM,data:bFk7V8xs6AibFGnYgaV3O+MkQXtmIb86s+ViKZn2n9lkRwznddhEL+lmxKdiECUiGZjKQRWb,iv:DTDTBgWSveBvdTc5XDf381j6KbPMcjO1pleD2rvGOYo=,tag:BnB/BFSuYxEkGlSRGa3lzw==,type:str]
    port: ENC[AES256_GCM,data:YOLC/A==,iv:dp5trDJeoj2K2YGX8ZElv7Ws708DPrqOJDMhd2I1gLo=,tag:fimRaDkwSWT8SEI2FpPGvQ==,type:str]
    name: ENC[AES256_GCM,data:lMXD6Pzr,iv:YpNBcLacNTNQ+oWOR74DDRWQbYYMmln135tHScE/zic=,tag:dZAUyLV72xwytq6osdnFww==,type:str]
    user: ENC[AES256_GCM,data:r2iGv+2X,iv:TU+F2WBkUH0jTF7+aQ/yxYd0W1KkWFZc7eU/TfOrIkk=,tag:au7yG5Vx6smJ6Oqs6gC4oQ==,type:str]
    userpass: ENC[AES256_GCM,data:oMhhzDL5,iv:whr0xWS8Qv6GctfHyz4anOIkIE46q7QvAlXYMBM7Y34=,tag:Nghf+u3rCttIT9IeX/WLJg==,type:str]
    adminpass: ENC[AES256_GCM,data:i+dv96Yr,iv:qstx+d1YmxveSj+5x18k/8ZUyxu74Ya+9sLCUvH5MME=,tag:dXYaKT5rOLFL4Annn2DMaQ==,type:str]
kafka:
    host: ENC[AES256_GCM,data:9ppcejX+6UHNwqaU4AApbkl9NRGXUHtuZF93u9+YfaRDDGfFRg==,iv:u2LhzcOP2x5tygo+7ltyl5V40J+pjNAMQhP0XFgllmU=,tag:nwoyTjp3ueyn4hJUEO4guQ==,type:str]
    port: ENC[AES256_GCM,data:24Udxg==,iv:G7DaPYNlfC6VqSiWPfrnEf2cOihOqFDbcmfVf6SLyX0=,tag:bxF08mZOe1HzkxLiQNDJOw==,type:str]
namespace: ENC[AES256_GCM,data:ISJ1o8qE,iv:mH3/hfW2Ia/ndT1I0AcWDoGYyGdYzV5cniuSzubJwbQ=,tag:thXPm2a0NIGZkEPcncdg/A==,type:str]
serviceName: ENC[AES256_GCM,data:NjgBnfdwKyWuTC7nUsM=,iv:0bX92+f280Kba7LeUr++Nc6i6/JmXo2apVbnxYIAYuM=,tag:CYfsPOwrPz2ApBWoUJEUjA==,type:str]
deploymentName: ENC[AES256_GCM,data:oMRfg+iy9ZCNSmfHnoPY5Fk=,iv:GMG+QHrQH6nXZPlVDnyf+TcuF/kNxxZ+sXyO2yFIBIg=,tag:sX7rMZeymDSlT0pyV8Ihtg==,type:str]
containerName: ENC[AES256_GCM,data:zHk7QB+bDIvLHQzYvPnnWA==,iv:5CoGjtI2DtVOfn1Q7QFs3jjD6/p1LhdSS7SPGFB1lJQ=,tag:XumWpt4dbxjtNQ1XCdnKKw==,type:str]
configName: ENC[AES256_GCM,data:CX0yxYWTZ1wja4dNnQ==,iv:ruY9oY5a9nqzpM9lZRMAoLkORnO+NyaGWNQt5NuZMkc=,tag:B2RJSQDnTtbf+GVcEMot8w==,type:str]
secretName: ENC[AES256_GCM,data:QTAHn5A8kOz0UH/lJBqBzMmI,iv:Ja2HBCDi3rknYGl249/4P6eScLR8WKT8hov1x7A0dCI=,tag:yBGNIpiWSoEouMjLo0dJEw==,type:str]
serviceMonitorName: ENC[AES256_GCM,data:J+yQFPR7N0cA4MLibTs=,iv:7YogpR6a7MhhzjG6XmXROoFLduM5IgexnZFFC8nRnKI=,tag:k5qjbffAogwB3Dz3jUVQGQ==,type:str]
serviceMonitorLabel: ENC[AES256_GCM,data:l0mTryBo7BiU9aVrY+4=,iv:yub7yjenh3RqtjgvIgVxpVj15nyHoWVXLHt5blz+KEM=,tag:jRJ6atoaCtbpt9MtSf7QkQ==,type:str]
image:
    repository: ENC[AES256_GCM,data:2ti83aUFRUT3B/zRCI/vORK09+GHQfOtfsXghHsWBZkCWcS8RNOghJIWMN97/5jLMCwARQVYAKA=,iv:8JbKfA02938DmJwMcZ2y0u1/VKwCdx0nZC2DT2IavxA=,tag:BOyQSjaESmxXB/50dtB7vQ==,type:str]
    tag: ENC[AES256_GCM,data:+5SXa+OZrkGGIsHVirmHyc5s14HyFDJN+VOlJdC2bNXYrndLKKsBEQ==,iv:AZggX7EWpvTadNotcRshQqs3hDLu2duBAW1BHSc9zvo=,tag:jj1J2v6UbyruPX/03PmgSA==,type:str]
deploy:
    replicasCount: ENC[AES256_GCM,data:eg==,iv:TwKwDsShvpGJ29UcB2258WB8SYqeblTSVQNg7R1ka0A=,tag:g9ku20a712Yyx8IVn2Krlw==,type:int]
    serviceLabel: ENC[AES256_GCM,data:0leQWKYF,iv:X6C4wSAt2sJdCLcKcK5AUK8wl3ZFQxzOidpsobuTdbg=,tag:fm2pxOy2NChalFZSXVL65A==,type:str]
    podLabel: ENC[AES256_GCM,data:xnvJSZnG,iv:6ne3K+mSZzS1Sh7a++Hs1AvtvDsI7u0/oPjc8dHnb8Q=,tag:puYERhsHpFoFu0AL+l17Ww==,type:str]
    deploymentLabel: ENC[AES256_GCM,data:PbyCazTv,iv:mgZrFNx1s1mixNtjCtzvpGsIDQjvLQqXBuxIQydz2VM=,tag:ii8qYorjOXnEaE+Y+SOMlg==,type:str]
    containerPort: ENC[AES256_GCM,data:jpU2AQ==,iv:rlzOmJ8aiJgOWzat98wg38yRKuGN8X7clrLL1qXdI68=,tag:SrqfHZRI0noRfq6X8pmcWQ==,type:int]
    service:
        type: ENC[AES256_GCM,data:VZ3p0QWObYpR,iv:BnlZT1PMJOzOCZDsINSTZNBjjykTpKrtN0LYJeDcjtw=,tag:1LQ6DxFN1pvOKVlvUyWrYw==,type:str]
        port:
            number: ENC[AES256_GCM,data:GYOp9Q==,iv:dJe0KljAJbyRvBSwZ0VOjNRuv46ZpyAbb1GyJRfZd6k=,tag:yPXjlVlmOjPx5zCqxiUNfw==,type:int]
            name: ENC[AES256_GCM,data:QCKr8fwi,iv:bZe+HAG0qkJNEDeyx3MzAm0B2phZEpq0YL3kludGv8c=,tag:YRuoJ13fMsecBb0ME6zCeg==,type:str]
        metricPort:
            number: ENC[AES256_GCM,data:l+gOkw==,iv:SIOEqeV6tOAhtTqWOtDAol39LtKPtpJVmTqwscP3n3Q=,tag:YJVtVjkPYrw2TqhGPDmsUQ==,type:int]
            name: ENC[AES256_GCM,data:PbK56091/AKrM3VUm3o=,iv:QGEsuCypIPtKyiyX7y9FX3brKmQkRXSbGcnDOojY2Fs=,tag:iF6B2ZBNlBCLLvGX1zR0Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yu4wcn3ykhlxfkne5te45v9vjcjuuv67h9ywl5kd09fnygr5df8q377uqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBandsQVdwbld4eUUyTEtm
            dWZSQjJTR2ZmRi9NV0NwVEtYK2lpYitMamdzCmpuRE9IdWIzclhpLys2RkVYbnZD
            WHlxckZJanRjOXB2djV1TERzU0E4V1UKLS0tIDB2R001K2laVlRlVnorR2xQaTF4
            VFAwRlF2dU9ib3hENVNIT1g1T1lGUmcKkMryh7MPe1htLZLqYzlGjjp0IszxG8ws
            JEAHmKx2CFNkKD5IQVklVz2e4M1aG7p1RD+AZXkRH4Y+LW/K92AQOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T18:03:51Z"
    mac: ENC[AES256_GCM,data:mzXU8SCPk1Q2lfEdlMiYmCaqlrVrMdXv5PuOrg0uzgcSWWGEMbK1BWlklgu7G0heb7LK7HExdfz+TqEcuvlXTn1VpeSoe7fB8EWf8nA7tHMdW/IFCqMozwFinEKnWW7YEdcB6atRb8hoB0W/lfHPVqesL1NQ/eROmEz0GUFge9k=,iv:OvUhSuvT2qbuVSf9cA8hN7tr5HkHKWMn4OCKbALzKeI=,tag:v/yw3poVG5gl72TtImLiHw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
