dataBase:
    host: ENC[AES256_GCM,data:IeYB6tVpeXMV80pV834TQpaexEjDKzpbmi0QMcA6PegdGh0zCG5xYi/dSMsf7tQlin2odQ==,iv:nzZgk0GEWmXlhIoPaiP33Xca8KqZw0XPRKlcx68jYh0=,tag:jmQvOWr4zxODru2D/R4SmQ==,type:str]
    port: ENC[AES256_GCM,data:ayZYJA==,iv:ON85mlH0RgOxS0gnLRbF5ORBKQk8GOHNbL2ORSRWDaE=,tag:KRzVFSeghRaxdavIX7n+DQ==,type:str]
    name: ENC[AES256_GCM,data:6Exmunw=,iv:uVdWL2ZOMsp4fdTNoTQSok/4Ia4Ae+SVHrW8TePCGTs=,tag:kv/29w7NF1OtxbEJixoH8g==,type:str]
    user: ENC[AES256_GCM,data:WV/gDKk=,iv:liit3miv3R5AlqSINm29WLk7gDW717Cy1soidgskwMw=,tag:tS6yD0CLj915GLYF6msTxw==,type:str]
    userpass: ENC[AES256_GCM,data:o/GG/eU=,iv:/vvryP0yos3VR8FtqZF+MY+4ouJfty9/8Xzu0LHpRfQ=,tag:aZjWR8nvNlqKs9jpe8FKDg==,type:str]
    adminpass: ENC[AES256_GCM,data:QRBC6+c=,iv:iYsI/lIMe4p4Z4bjoDh1dronma7hgFJTxzitBsd28BM=,tag:DPjmLuwvdGmPNeATPdzH3w==,type:str]
kafka:
    host: ENC[AES256_GCM,data:M8ibEDBJPUprDMo2qA1VAQZXyb9R3UPsbXEP6ua8fLLmJYtgrg==,iv:bwDSXAW08dkRxtSwVaKgQdb1RUznash/Kor5GJzP0EE=,tag:HJz6o4tAgBvGXVJ5fZJu5Q==,type:str]
    port: ENC[AES256_GCM,data:Qs+9Ow==,iv:DLO6GD0Unl9/7FZ4hBwAPEMXNGVbDTxb7mxjAcVDYmw=,tag:QPiifzMd53T+qSG2Upzl7A==,type:str]
namespace: ENC[AES256_GCM,data:oNxDxy4=,iv:XOw6OPMDnAnxf549B0xkFLs+EZ8g744MJkouyVQ6tWk=,tag:/fUEJiS1b6UW4Hfvy29FlA==,type:str]
serviceName: ENC[AES256_GCM,data:O4U0wvDN9uXR0qguMw==,iv:8rDVPJSocz5AhFkE1tBkHtnI1em/bqsDl90vD556ZCw=,tag:jwtdSvWzM/ekJbMUL5ytBw==,type:str]
deploymentName: ENC[AES256_GCM,data:RH4L7bfQStWCoKU+MCemCw==,iv:zu0UvgZmWaRB+6D3fmURKjXYakx7T/FdXyY5q4IMs/I=,tag:yyPa52fSx7qhTPUH8jsnWA==,type:str]
containerName: ENC[AES256_GCM,data:hQmWooBzlJyn/vZvqKzc,iv:dP8s2Oj5QExOe8J6sW4TrGFEQQKQ+NhYpjZ7UdapBns=,tag:Qri4G+UgvIdENsmywbNOPQ==,type:str]
configName: ENC[AES256_GCM,data:jFl8BNSdMDnQu0W8,iv:r65XInUQUXRdFj4aaD5flhVIafTL0+BneDuOdtHtWqU=,tag:oruxEbzbK49t9WWnBnoMKA==,type:str]
secretName: ENC[AES256_GCM,data:nxt1AJIaIxJ2xBqjkLe+42M=,iv:owogGYMBXDXErHndyXaappKTdBh9jUnIhnqkHz7/mSY=,tag:sATOKP8SS8+EIFf5aWLOqA==,type:str]
serviceMonitorName: ENC[AES256_GCM,data:10wPr4IqkJTpWm3k0w==,iv:EkmS0Q/6T9Dc/b5rWr9WEGdlU2tOTqJ8vOVmUtx6n0Q=,tag:/Kzqw7GYzV/lpXL6hxHd6A==,type:str]
serviceMonitorLabel: ENC[AES256_GCM,data:vaU1g98R/cr/YLGiXQ==,iv:bB9fDt44HeWWv9OZcy53umpy11YKDpYxBQYuCUKweeY=,tag:WqKaLXMpQ7apIvMLor7jyg==,type:str]
image:
    repository: ENC[AES256_GCM,data:7O4GtV5dQS7jDf8vGtXijIlxvR6Y5s0DK0MaS9JDm9IaQYp2dzcNdlrlLm+IMdL1MFBfF6aR4Q==,iv:mEz6IdBNLZm8cK3Irm9iNE4/KHrYyDA3fgreizsW3LA=,tag:+aBb1DyZzrmQkGy5N3MF1A==,type:str]
    tag: ENC[AES256_GCM,data:SRQgyQdjG5VbuHmWz/LLC2a5D6KJ6wncp4FJ2DfGDiFQ8pFvwei54g==,iv:8JOaReCbOteRXCHEGm786z5x7x4G+yUoRZJE7k4XLbM=,tag:876hVLc3ulcxlghISRy2Ew==,type:str]
deploy:
    replicasCount: ENC[AES256_GCM,data:3w==,iv:1Vhl4gvQrrKvtUZyYluNpCbcDt0A8jhgjEygPZkmVtw=,tag:Xsvk2R6nS4DQ0f/A/IcKag==,type:int]
    serviceLabel: ENC[AES256_GCM,data:wMp+FI0=,iv:9QYQJ8wTVrHbDb3+46Y6zv0gmF4jVfUXeWEPJR6oQz4=,tag:K0DfpPqiARFlVSjvuW1O8Q==,type:str]
    podLabel: ENC[AES256_GCM,data:sbOJU5w=,iv:g3MRi68N8XUX/IS4Uj/HLaVshfKjJ/zvIPzqnxqKaNc=,tag:f580o8CLuo3r8QHeCXoJqw==,type:str]
    deploymentLabel: ENC[AES256_GCM,data:eQBUUaE=,iv:GGMVKjgEcM5G+/q7ou+HlXS3y6UUEB9dkBtk/IOAXyY=,tag:/Fbz4FYWTceQ5AnmKyEI5g==,type:str]
    containerPort: ENC[AES256_GCM,data:j4c8eQ==,iv:Bp93w6idrTSuL4VTvgRUyVZkBf/LG7GF3hqXVowWriM=,tag:UGrTqXuwVxHDpyGY+0KLpw==,type:int]
    service:
        type: ENC[AES256_GCM,data:iFj3dWd+pb/+,iv:017doi07lJ4GQujJMAm8U+6SfkjgbOv09m5ck7CB+Fk=,tag:95cC/kUeuV7AfCdJc0nJJA==,type:str]
        port:
            number: ENC[AES256_GCM,data:u8G56Q==,iv:IXeJseJ6cUnuM5FsN5PEz3cGPEjejgCYbcmlHbz9oxY=,tag:1HRrMjbfomt2J5vjlbljsA==,type:int]
            name: ENC[AES256_GCM,data:WNcQEgo=,iv:0FT3zw7wThQr/7hDXmJlrOILB1r+xBmlofaQxMS8rVw=,tag:ijGmd1TjcxZczAXE8qDffw==,type:str]
        metricPort:
            number: ENC[AES256_GCM,data:/QEQEg==,iv:P9wCU49aO5j0jhismMxGTxV4WNHdNcKkfr7WFqiaRW0=,tag:ovORMDbcY9B9ZhVa521cLA==,type:int]
            name: ENC[AES256_GCM,data:09Vshx4uGE6zFk0q/A==,iv:GNlfRmtOBocC3aHgmbJkfb6jGLPI2sxDT+BUzjxd7Nc=,tag:RwKf1IFvOURyjLrhTIRbgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yu4wcn3ykhlxfkne5te45v9vjcjuuv67h9ywl5kd09fnygr5df8q377uqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZjZsRzhJWHhOTUpLZ2Ro
            Qk1ZaUliK0xUOVZQY3lEL01UdStDTHhTdkJjCmRVaXRmTUV6NGZrQWhpWU1aT096
            TEF2aDVGWFlBMklsYWYra2M3aVlQRTQKLS0tIDVSWDRSSUFzZDJaN1RRQUJPdTRj
            Z1luMWdPdmtTS1FPUXlUZGcyakc1NFkKrwDK1VRrPwud0uaoWNQA+E2pH6FmHZ2J
            7uOwTBL2FBQXIXjjDpaQtDfXCu3+HFLAMTRteGTnr65rzSofAQKxEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T18:26:07Z"
    mac: ENC[AES256_GCM,data:h1wM6BSILcDmK3UvW1secSLKvA1pbEF+4AQTCy72UdK96ZVGLzimLIyH1+wiwG51Qu1JJTcFxpSf+BVgK8IifGfPJ2EgRwjISlDCh81rMUg+YFpIJi6iRomsdOjm4GP2WE9ADGmjNhUDT/Xvd5idIegQRL5KCdBMp+svVveuD10=,iv:vbLOi44qCAmMsz//V2qAvBPWcx7OqLngjRWOa+ZcCLA=,tag:Nru1cRLpamNVf/yGIojh5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
