# Создаем неймспейс для gitlab-runner
apiVersion: v1
kind: Namespace
metadata:
  name: appeal
  annotations:
    # С помощью этого параметра указываем порядок создания
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appeal-service
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/appeal.update-strategy: latest
    argocd-image-updater.argoproj.io/image-list: appeal=cr.yandex/crp6r4552fomhn1v2lgu/andrey4281/appeal-service
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: appeal
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/backend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # Указываем путь до файла
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/appeal-service-values.yaml
  syncPolicy:
    automated: {}