# Создаем неймспейс для gitlab-runner
apiVersion: v1
kind: Namespace
metadata:
  name: doctor
  annotations:
    # С помощью этого параметра указываем порядок создания
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doctor-service
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/doctor.update-strategy: latest
    argocd-image-updater.argoproj.io/image-list: doctor=cr.yandex/crp6r4552fomhn1v2lgu/andrey4281/doctor-service
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: doctor
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/backend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # Указываем путь до файла
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/doctor-service-values.yaml
  syncPolicy:
    automated: {}