# Создаем неймспейс для gitlab-runner
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    # С помощью этого параметра указываем порядок создания
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/kube-prometheus-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}